//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: MarketPlace.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol Marketplace_MarketPlacecheckoutCall: ClientCallUnary {}

fileprivate final class Marketplace_MarketPlacecheckoutCallBase: ClientCallUnaryBase<Marketplace_CheckOutRequest, Marketplace_CheckOutResult>, Marketplace_MarketPlacecheckoutCall {
  override class var method: String { return "/marketplace.MarketPlace/checkout" }
}

internal protocol Marketplace_MarketPlacegetAllOrdersCall: ClientCallUnary {}

fileprivate final class Marketplace_MarketPlacegetAllOrdersCallBase: ClientCallUnaryBase<Marketplace_GetAllOrdersRequest, Marketplace_GetAllOrdersResult>, Marketplace_MarketPlacegetAllOrdersCall {
  override class var method: String { return "/marketplace.MarketPlace/getAllOrders" }
}

internal protocol Marketplace_MarketPlacehandleGetOrgItemsCall: ClientCallUnary {}

fileprivate final class Marketplace_MarketPlacehandleGetOrgItemsCallBase: ClientCallUnaryBase<Marketplace_GetOrgItemsRequest, Marketplace_GetOrgItemsResult>, Marketplace_MarketPlacehandleGetOrgItemsCall {
  override class var method: String { return "/marketplace.MarketPlace/handleGetOrgItems" }
}


/// Instantiate Marketplace_MarketPlaceServiceClient, then call methods of this protocol to make API calls.
internal protocol Marketplace_MarketPlaceService: ServiceClient {
  /// Synchronous. Unary.
  func checkout(_ request: Marketplace_CheckOutRequest, metadata customMetadata: Metadata) throws -> Marketplace_CheckOutResult
  /// Asynchronous. Unary.
  @discardableResult
  func checkout(_ request: Marketplace_CheckOutRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_CheckOutResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacecheckoutCall

  /// Synchronous. Unary.
  func getAllOrders(_ request: Marketplace_GetAllOrdersRequest, metadata customMetadata: Metadata) throws -> Marketplace_GetAllOrdersResult
  /// Asynchronous. Unary.
  @discardableResult
  func getAllOrders(_ request: Marketplace_GetAllOrdersRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_GetAllOrdersResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacegetAllOrdersCall

  /// Synchronous. Unary.
  func handleGetOrgItems(_ request: Marketplace_GetOrgItemsRequest, metadata customMetadata: Metadata) throws -> Marketplace_GetOrgItemsResult
  /// Asynchronous. Unary.
  @discardableResult
  func handleGetOrgItems(_ request: Marketplace_GetOrgItemsRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_GetOrgItemsResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleGetOrgItemsCall

}

internal extension Marketplace_MarketPlaceService {
  /// Synchronous. Unary.
  func checkout(_ request: Marketplace_CheckOutRequest) throws -> Marketplace_CheckOutResult {
    return try self.checkout(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func checkout(_ request: Marketplace_CheckOutRequest, completion: @escaping (Marketplace_CheckOutResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacecheckoutCall {
    return try self.checkout(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getAllOrders(_ request: Marketplace_GetAllOrdersRequest) throws -> Marketplace_GetAllOrdersResult {
    return try self.getAllOrders(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getAllOrders(_ request: Marketplace_GetAllOrdersRequest, completion: @escaping (Marketplace_GetAllOrdersResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacegetAllOrdersCall {
    return try self.getAllOrders(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func handleGetOrgItems(_ request: Marketplace_GetOrgItemsRequest) throws -> Marketplace_GetOrgItemsResult {
    return try self.handleGetOrgItems(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func handleGetOrgItems(_ request: Marketplace_GetOrgItemsRequest, completion: @escaping (Marketplace_GetOrgItemsResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleGetOrgItemsCall {
    return try self.handleGetOrgItems(request, metadata: self.metadata, completion: completion)
  }

}

internal final class Marketplace_MarketPlaceServiceClient: ServiceClientBase, Marketplace_MarketPlaceService {
  /// Synchronous. Unary.
  internal func checkout(_ request: Marketplace_CheckOutRequest, metadata customMetadata: Metadata) throws -> Marketplace_CheckOutResult {
    return try Marketplace_MarketPlacecheckoutCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func checkout(_ request: Marketplace_CheckOutRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_CheckOutResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacecheckoutCall {
    return try Marketplace_MarketPlacecheckoutCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getAllOrders(_ request: Marketplace_GetAllOrdersRequest, metadata customMetadata: Metadata) throws -> Marketplace_GetAllOrdersResult {
    return try Marketplace_MarketPlacegetAllOrdersCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func getAllOrders(_ request: Marketplace_GetAllOrdersRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_GetAllOrdersResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacegetAllOrdersCall {
    return try Marketplace_MarketPlacegetAllOrdersCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func handleGetOrgItems(_ request: Marketplace_GetOrgItemsRequest, metadata customMetadata: Metadata) throws -> Marketplace_GetOrgItemsResult {
    return try Marketplace_MarketPlacehandleGetOrgItemsCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func handleGetOrgItems(_ request: Marketplace_GetOrgItemsRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_GetOrgItemsResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleGetOrgItemsCall {
    return try Marketplace_MarketPlacehandleGetOrgItemsCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

