//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: MarketPlace.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol Marketplace_MarketPlacehandleAddItemsCall: ClientCallUnary {}

fileprivate final class Marketplace_MarketPlacehandleAddItemsCallBase: ClientCallUnaryBase<Marketplace_AddItemRequest, Marketplace_AddItemResult>, Marketplace_MarketPlacehandleAddItemsCall {
  override class var method: String { return "/marketplace.MarketPlace/handleAddItems" }
}

internal protocol Marketplace_MarketPlacehandleGetOrgItemsCall: ClientCallUnary {}

fileprivate final class Marketplace_MarketPlacehandleGetOrgItemsCallBase: ClientCallUnaryBase<Marketplace_GetOrgItemsRequest, Marketplace_GetOrgItemsResult>, Marketplace_MarketPlacehandleGetOrgItemsCall {
  override class var method: String { return "/marketplace.MarketPlace/handleGetOrgItems" }
}

internal protocol Marketplace_MarketPlacehandleCheckoutCall: ClientCallUnary {}

fileprivate final class Marketplace_MarketPlacehandleCheckoutCallBase: ClientCallUnaryBase<Marketplace_CheckOutRequest, Marketplace_CheckOutResult>, Marketplace_MarketPlacehandleCheckoutCall {
  override class var method: String { return "/marketplace.MarketPlace/handleCheckout" }
}

internal protocol Marketplace_MarketPlacehandleGetSimilarItemsCall: ClientCallUnary {}

fileprivate final class Marketplace_MarketPlacehandleGetSimilarItemsCallBase: ClientCallUnaryBase<Marketplace_GetSimilarItemsRequest, Marketplace_GetSimilarItemsResult>, Marketplace_MarketPlacehandleGetSimilarItemsCall {
  override class var method: String { return "/marketplace.MarketPlace/handleGetSimilarItems" }
}


/// Instantiate Marketplace_MarketPlaceServiceClient, then call methods of this protocol to make API calls.
internal protocol Marketplace_MarketPlaceService: ServiceClient {
  /// Synchronous. Unary.
  func handleAddItems(_ request: Marketplace_AddItemRequest, metadata customMetadata: Metadata) throws -> Marketplace_AddItemResult
  /// Asynchronous. Unary.
  @discardableResult
  func handleAddItems(_ request: Marketplace_AddItemRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_AddItemResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleAddItemsCall

  /// Synchronous. Unary.
  func handleGetOrgItems(_ request: Marketplace_GetOrgItemsRequest, metadata customMetadata: Metadata) throws -> Marketplace_GetOrgItemsResult
  /// Asynchronous. Unary.
  @discardableResult
  func handleGetOrgItems(_ request: Marketplace_GetOrgItemsRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_GetOrgItemsResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleGetOrgItemsCall

  /// Synchronous. Unary.
  func handleCheckout(_ request: Marketplace_CheckOutRequest, metadata customMetadata: Metadata) throws -> Marketplace_CheckOutResult
  /// Asynchronous. Unary.
  @discardableResult
  func handleCheckout(_ request: Marketplace_CheckOutRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_CheckOutResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleCheckoutCall

  /// Synchronous. Unary.
  func handleGetSimilarItems(_ request: Marketplace_GetSimilarItemsRequest, metadata customMetadata: Metadata) throws -> Marketplace_GetSimilarItemsResult
  /// Asynchronous. Unary.
  @discardableResult
  func handleGetSimilarItems(_ request: Marketplace_GetSimilarItemsRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_GetSimilarItemsResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleGetSimilarItemsCall

}

internal extension Marketplace_MarketPlaceService {
  /// Synchronous. Unary.
  func handleAddItems(_ request: Marketplace_AddItemRequest) throws -> Marketplace_AddItemResult {
    return try self.handleAddItems(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func handleAddItems(_ request: Marketplace_AddItemRequest, completion: @escaping (Marketplace_AddItemResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleAddItemsCall {
    return try self.handleAddItems(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func handleGetOrgItems(_ request: Marketplace_GetOrgItemsRequest) throws -> Marketplace_GetOrgItemsResult {
    return try self.handleGetOrgItems(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func handleGetOrgItems(_ request: Marketplace_GetOrgItemsRequest, completion: @escaping (Marketplace_GetOrgItemsResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleGetOrgItemsCall {
    return try self.handleGetOrgItems(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func handleCheckout(_ request: Marketplace_CheckOutRequest) throws -> Marketplace_CheckOutResult {
    return try self.handleCheckout(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func handleCheckout(_ request: Marketplace_CheckOutRequest, completion: @escaping (Marketplace_CheckOutResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleCheckoutCall {
    return try self.handleCheckout(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func handleGetSimilarItems(_ request: Marketplace_GetSimilarItemsRequest) throws -> Marketplace_GetSimilarItemsResult {
    return try self.handleGetSimilarItems(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func handleGetSimilarItems(_ request: Marketplace_GetSimilarItemsRequest, completion: @escaping (Marketplace_GetSimilarItemsResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleGetSimilarItemsCall {
    return try self.handleGetSimilarItems(request, metadata: self.metadata, completion: completion)
  }

}

internal final class Marketplace_MarketPlaceServiceClient: ServiceClientBase, Marketplace_MarketPlaceService {
  /// Synchronous. Unary.
  internal func handleAddItems(_ request: Marketplace_AddItemRequest, metadata customMetadata: Metadata) throws -> Marketplace_AddItemResult {
    return try Marketplace_MarketPlacehandleAddItemsCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func handleAddItems(_ request: Marketplace_AddItemRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_AddItemResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleAddItemsCall {
    return try Marketplace_MarketPlacehandleAddItemsCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func handleGetOrgItems(_ request: Marketplace_GetOrgItemsRequest, metadata customMetadata: Metadata) throws -> Marketplace_GetOrgItemsResult {
    return try Marketplace_MarketPlacehandleGetOrgItemsCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func handleGetOrgItems(_ request: Marketplace_GetOrgItemsRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_GetOrgItemsResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleGetOrgItemsCall {
    return try Marketplace_MarketPlacehandleGetOrgItemsCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func handleCheckout(_ request: Marketplace_CheckOutRequest, metadata customMetadata: Metadata) throws -> Marketplace_CheckOutResult {
    return try Marketplace_MarketPlacehandleCheckoutCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func handleCheckout(_ request: Marketplace_CheckOutRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_CheckOutResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleCheckoutCall {
    return try Marketplace_MarketPlacehandleCheckoutCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func handleGetSimilarItems(_ request: Marketplace_GetSimilarItemsRequest, metadata customMetadata: Metadata) throws -> Marketplace_GetSimilarItemsResult {
    return try Marketplace_MarketPlacehandleGetSimilarItemsCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func handleGetSimilarItems(_ request: Marketplace_GetSimilarItemsRequest, metadata customMetadata: Metadata, completion: @escaping (Marketplace_GetSimilarItemsResult?, CallResult) -> Void) throws -> Marketplace_MarketPlacehandleGetSimilarItemsCall {
    return try Marketplace_MarketPlacehandleGetSimilarItemsCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

